# Trigger pipeline for specific branches
trigger:
  branches:
    include:
      - main
      - feature/*

# Pull Request Validation
pr:
  branches:
    include:
      - main

# Pipeline Stages
stages:
  # Build Stage
  - stage: Build
    displayName: "Build Solution"
    jobs:
      - job: Build
        displayName: "Build Job"
        pool:
          vmImage: 'windows-latest'
        steps:
          # Install .NET SDK
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '6.x'

          # Restore NuGet Packages
          - task: NuGetCommand@2
            inputs:
              command: 'restore'
              restoreSolution: 'Portal.sln'

          # Build the Solution
          - task: VSBuild@1
            inputs:
              solution: 'Portal.sln'
              msbuildArgs: '/p:Configuration=Release'

  # Test Stage
  - stage: Test
    displayName: "Run Automated Tests"
    dependsOn: Build
    jobs:
      - job: Test
        displayName: "Run Tests"
        pool:
          vmImage: 'windows-latest'
        variables:
          TestCategory: "API_VerifyAuthenticationRequired" # Default Test Category
        steps:
          # Run Tests
          - task: VSTest@2
            inputs:
              testSelector: 'testAssemblies'
              testAssemblyVer2: '**/bin/Release/*.dll'
              searchFolder: '$(System.DefaultWorkingDirectory)'
              otherConsoleOptions: '/TestCaseFilter:"TestCategory=$(TestCategory)"'
